apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  annotations:
    sidecar.istio.io/inject: "false"
  labels:
    run: amicontained
  name: amicontained2
spec:
  securityContext:
    seccompProfile:
      type: Localhost
      localhostProfile: <path to custom JSON file on host, relative to default path>
  containers:
  - args:
    - amicontained
    image: r.j3ss.co/amicontained
    name: amicontained
    resources: {}
    securityContext:
      allowPrivilegeEscalation: false
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
